import LoginPage from "@/components/login/Login";
import { getUserInfo } from "@/services/auth.service";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "University Management/Login",
  description: "Generated by University Management",
};

const Login = () => {
  return (
    <div>
      <LoginPage></LoginPage>
    </div>
  );
};

export default Login;
