import SingUp from "@/components/signup/SingUp";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "University Management/Singup",
  description: "Generated by University Management",
};

const SingUpPage = () => {
  return (
    <>
      <SingUp></SingUp>
    </>
  );
};
export default SingUpPage;
